# Require JSON module
require 'json'
 
# Read YAML file with box details
servers = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'servers.json')))

Vagrant.configure(2) do |config|
	# Ubuntu 14.04
	config.vm.box = "ubuntu/trusty64"
	config.vm.synced_folder "../project/", "/home/vagrant/project", :mount_options => ["dmode=777", "fmode=777"]


	servers.each do |server|
    config.vm.define server['name'] do |srv|
      srv.vm.hostname = server['name']

      srv.vm.network 'private_network', ip: server['ip_addr']
      srv.vm.network "forwarded_port",guest: server['fp_guest1'],host: server['fp_host1'], id: 'ssh', auto_correct: true
      srv.vm.network "forwarded_port",guest: server['fp_guest2'],host: server['fp_host2']
      srv.ssh.forward_agent = true 

      srv.vm.provider "virtualbox" do |vmw|
        vmw.memory = server['ram']
      end # srv.vm.provider
    end # config.vm.define
  end # servers.each


 # Puppet e shell provisioning
  config.vm.provision :shell do |shell|
		shell.inline = "mkdir -p /etc/puppet/modules;
    		      puppet module install puppetlabs/apt
                      puppet module install puppetlabs-postgresql"
    end
    
	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "puppet/manifests"
		puppet.manifest_file = "site.pp"
		puppet.module_path = "puppet/modules"
	end

end
